### PR TITLE
[FRS-89] Fix incompatibility with the new version of Flink

### LINKED ISSUE #89: Incompatibility with the new version of Flink
The compile process will be failed with the new version of Flink because the following issue.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:53 min
[INFO] Finished at: 2022-11-25T22:00:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project shuffle-plugin: Compilation failure
[ERROR] /home/github/flink-remote-shuffle/shuffle-plugin/src/main/java/com/alibaba/flink/shuffle/plugin/transfer/RemoteShuffleInputGate.java:[731,38] incompatible types: java.net.InetSocketAddress cannot be converted to org.apache.flink.runtime.taskmanager.TaskManagerLocation
[ERROR]
[ERROR] -> [Help 1]
```

The failed reason is that FLINK ConnectionID construction method is changed because of [FLINK-29639](https://issues.apache.org/jira/browse/FLINK-29639).

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
## What is the purpose of the change

*Fix incompatibility with the new version of Flink*

This change will not affect the compatibility of RSS and lower versions of Flink. Because Flink ConnectionID has two construction methods, only one of which has changed. Previously, it was affected because the construction method used was changed. Now it is changed to the ConnectionID construction method that has not changed for several years, so it is compatible with the historical version of Flink.

## Brief change log
  - Modify the FakedRemoteInputChannel construction method.

## Verifying this change

This change is a trivial code cleanup without any test coverage.

### CODE REVIEW

File: shuffle-plugin/src/main/java/com/alibaba/flink/shuffle/plugin/transfer/RemoteShuffleInputGate.java [hunk 1]
```diff
@@ -728,7 +731,10 @@ private class FakedRemoteInputChannel extends RemoteInputChannel {
                     channelIndex,
                     new ResultPartitionID(),
                     0,
-                    new ConnectionID(new InetSocketAddress("", 0), 0),
+                    new ConnectionID(
+                            new TaskManagerLocation(
+                                    new ResourceID(""), InetAddress.getLoopbackAddress(), 1),
```
Comment (reswqa) [inline shuffle-plugin/src/main/java/com/alibaba/flink/shuffle/plugin/transfer/RemoteShuffleInputGate.java:736]:
```suggestion
                        ResourceID.generate(), InetAddress.getLoopbackAddress(), 1),
```

**Review by reswqa — APPROVED** [review]
@TanYuxin-tyx Thanks for the fix, LGTM.

**Review by wsry — APPROVED** [review]
